// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestAppAngular.Models;

namespace TestAppAngular.Migrations
{
    [DbContext(typeof(Informationcontext))]
    [Migration("20211121085037_InformationMigration")]
    partial class InformationMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TestAppAngular.Models.Information", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BreadText")
                        .HasMaxLength(300);

                    b.Property<string>("Footer")
                        .HasMaxLength(80);

                    b.Property<string>("HeadLine")
                        .HasMaxLength(80);

                    b.HasKey("Id");

                    b.ToTable("Information");
                });
#pragma warning restore 612, 618
        }
    }
}
